### ISSUE TITLE
tpm installation not working

### ISSUE THREAD

**Issue by qrockz** [catppuccin/tmux#149] opened 2024-03-05 15:44 UTC
![screenshot](https://github.com/catppuccin/tmux/assets/56853194/a1adc17a-647a-45ca-86e3-59f1a58c3107)

```
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g status-position top

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"
run '~/.config/tmux/plugins/tpm/tpm'
```
Prefix+Alt+U

catppuccin is not listed

Previously I had installed dracula theme and I think it's is still interfering with cattpuccin somehow (notice the battery, wlan,weather module loaded on the right side of the window panel which I had used in dracula)

**Comment by gbitim** [comment] 2024-03-05 16:03
I've just experienced the exact same thing and what I think it is, is that both of these ultimately install to a directory named "tmux".

`set -g @plugin 'catppuccin/tmux'`
and
`set -g @plugin 'dracula/tmux'`

Both result in a directory (in my case in ~/.config/tmux/plugins) named tmux. If it still exists, it will not be overwritten, it appears, nor will the contents be replaced (at least, not in a way that works).

I rm -rf'd the directory and then tried again and it now seems to be working for me.

**Comment by shadow-absorber** [comment] 2024-03-05 21:12
> Why the heck is this plugin listed as "tmux" in tpm and not as "cattpuccin" !? It's confusing.

because tpm names the plugins after the name of the project and not after the name of the group/user who made the project... which yeah it should use both but it is not something catppuccin can change unless they change the name of this project

**Comment by shadow-absorber** [comment] 2024-03-06 00:47
the issue #129 is relevant for this too

**Comment by sgoudham** [comment] 2024-03-06 23:48
Closing as root cause is a duplicate of #129

**Closed by sgoudham** 2024-03-06 23:48 UTC
