### ISSUE TITLE
Theme isn't installing when I press Ctrl + b followed by capital I

### ISSUE THREAD

**Issue by JwanKhalaf** [catppuccin/tmux#120] opened 2024-01-24 12:51 UTC
Hello

Here's [my config.](https://github.com/JwanKhalaf/.dotfiles/blob/main/.config/tmux/tmux.conf).

When I press Ctrl + b followed by capital I, I get shown this:

![image](https://github.com/catppuccin/tmux/assets/42877376/ec2610a4-3881-4b8e-8443-134aadd903cc)

But the Tmux's look doesn't update! For some reason, I still see this:

![image](https://github.com/catppuccin/tmux/assets/42877376/cdbe2f70-18ff-413a-a917-c86c12fcf1ca)

What am I missing? I of course tried re-sourcing the config:

```
 tmux source ~/.config/tmux/tmux.conf
```

I also tried rebooting, but nothing seems to work. Also, when I look at `~/.config/tmux/plugins` I do not see catppuccin listed!

```
~ ❯ l ~/.config/tmux/plugins
Permissions Size User Group Date Modified Name
drwxr-xr-x     - j    j     24 Jan 07:59  tmux
drwxr-xr-x     - j    j     24 Jan 07:59  tmux-sensible
drwxr-xr-x     - j    j     24 Jan 07:59  tmux-yank
drwxr-xr-x     - j    j     24 Jan 12:15  tpm
drwxr-xr-x     - j    j     24 Jan 07:59  vim-tmux-navigator
~ ❯
```

**Comment by igops** [comment] 2024-01-25 11:00
same problem 👍

**Comment by bwbuhse** [comment] 2024-01-25 16:33
Same here; the exact same config worked on my laptop a while ago but I've been trying to get tmux set up on my desktop and now it won't install.

```unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -n C-k clear-history

# set shell
# set -g default-shell /usr/bin/zsh
# set -g default-command /usr/bin/fish

# set term to tmux instead of gnu screen
# this enables proper italics support
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"

setw -g mode-keys vi

set-option -g status-position top

# List of plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @catppuccin_flavour 'mocha'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

**Comment by igops** [comment] 2024-01-28 10:28
@pocco81 @89iuv any thoughts guys?

**Comment by 89iuv** [comment] 2024-01-29 05:19
Can you try to load tpm before you load catppuccin?

Ex:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
```

**Comment by igops** [comment] 2024-01-29 12:59
> Can you try to load tpm before you load catppuccin?
> 
> Ex:
> 
> ```
> set -g @plugin 'tmux-plugins/tpm'
> set -g @plugin 'catppuccin/tmux'
> 
> set -g @plugin 'tmux-plugins/tmux-sensible'
> set -g @plugin 'tmux-plugins/tmux-pain-control'
> ```

It doesn't work at all :(

**Comment by JwanKhalaf** [comment] 2024-01-29 14:26
@89iuv where would the catppuccin folder be? I can't see it under `~/.config/tmux/plugins`.

**Comment by bwbuhse** [comment] 2024-01-29 15:45
For me, catppuccin is in neither of those places.

```
~ 
❯ eza -l ~/.config/tmux/plugins                                                               
drwxr-xr-x - ben 13 Nov  2023 tmux
drwxr-xr-x - ben 19 Nov  2023 tmux-pain-control
drwxr-xr-x - ben 13 Nov  2023 tmux-sensible
drwxr-xr-x - ben 13 Nov  2023 tpm

~ 
❯ eza -l ~/.tmux/plugins       
drwxr-xr-x - ben 24 Jan 17:15 tpm
```

Similarly, when I do `^a + I` I get 
```
Already installed "tmux"                                                                                                                [0/0]
Already installed "tpm"            
Already installed "tmux-sensible"  
Already installed "tmux-pain-control"                                 

TMUX environment reloaded.  
```
with no mention of Catppuccin, even though it's in my config. I've also tried with it before and after the tpm line.

**Comment by 89iuv** [comment] 2024-01-29 15:48
The name of the catppuccin folder is called "tmux"

Please run: ``` ls -al ~/.config/tmux/plugins/tmux``` and provide the output.

**Comment by JwanKhalaf** [comment] 2024-01-29 15:51
Here's what I get:

```
~/.config/tmux/plugins/tmux main ❯ ls -lah
total 0
drwxr-xr-x 1 j j  0 Jan 24 07:59 .
drwxr-xr-x 1 j j 94 Jan 24 12:39 ..
~/.config/tmux/plugins/tmux main ❯
```

**Comment by bwbuhse** [comment] 2024-01-29 15:54
Seems like after running the update all it still didn't work (said it was up to date), but *then* removing the `tmux` directory under `../plugins` and running `ctrl+a I` again did install it correctly... ? \*shrug\*

**Comment by 89iuv** [comment] 2024-01-29 16:00
> Seems like after running the update all it still didn't work (said it was up to date), but _then_ removing the `tmux` directory under `../plugins` and running `ctrl+a I` again did install it correctly... ? *shrug*

I think that somehow TPM created an empty "tmux" directory in the plugins folder (why this happened i do not know). This created the issue above and the only solution seems to be to remove the "tmux" directory from plugins and reinstall the plugin.

**Comment by JwanKhalaf** [comment] 2024-01-29 16:09
Can confirm. Removing the directory with `rm -rf ~/.config/tmux/plugins/tmux` then re-doing `ctrl + b I` got the theme installed and showing again! 🎉 Thanks all

**Comment by igops** [comment] 2024-01-29 19:04
Confirm removing tmux plugin resolves the issue.

How came the `catppuccin` plugin called `tmux`? 😱 
This is sooooo confusing guys!

**Comment by marcusps** [comment] 2024-03-03 04:24
https://github.com/tmux-plugins/tpm/issues/273 is closely related -- this may be better thought of as a `tpm` issue.  There is a PR https://github.com/tmux-plugins/tpm/pull/274 under review that would fix it.

**Comment by sgoudham** [comment] 2024-03-06 23:48
Closing as root cause is a duplicate of #129

**Closed by sgoudham** 2024-03-06 23:48 UTC

**Comment by YugandharrPatil** [comment] 2025-01-23 06:53
updating all plugins fixed it for me. but the behavior is for sure finicky, needs fixing.

**Comment by kjnsn** [comment] 2025-01-23 07:04
> updating all plugins fixed it for me. but the behavior is for sure finicky, needs fixing.

You can try raising another issue on tpm, but it hasn't been maintained in over two years.
