### ISSUE TITLE
[HELP] my configuration is broken after updating

### ISSUE THREAD

**Issue by 89iuv** [catppuccin/tmux#58] opened 2023-08-09 13:00 UTC
Hi all, 

Because of the masive refactoring done on this repo some of the previous configurations do not working anymore.
PR with the refactoring and list of settings removed: https://github.com/catppuccin/tmux/pull/57

If you have trouble transitioning from the old config to the new one please reply here and i will do my best to help you.

Thank you.

**Comment by deepanchal** [comment] 2023-08-10 14:37
Thanks for the refactor @89iuv :)
I found a minor issue with config 3 in README and have opened a PR with the fix: https://github.com/catppuccin/tmux/pull/63

**Comment by evanleck** [comment] 2023-08-11 19:40
I dig the refactor and flexibility provided by it, but it's really odd looking without a patched font and there's not an example in the README that doesn't seem to rely on patched fonts.

I've got most of my config migrated to use the variables but I can't seem to get rid of these question marks in the status area. I've tried setting things like `catppuccin_date_time_icon` or `catppuccin_status_left_separator` to `""` but nothing seems to work. What am I missing here?

<img width="424" alt="Screenshot 2023-08-11 at 12 37 22 PM" src="https://github.com/catppuccin/tmux/assets/21947/416daf1d-97bd-40a9-b654-9dd86d32f9c2">

**Comment by 89iuv** [comment] 2023-08-11 20:10
@evanleck did a test and it does not work on my side. I will work on implementing a fix for it next week.

**Comment by assignUser** [comment] 2023-08-12 23:47
@89iuv I installed this theme a while ago and was trying out new config stuff but it didn't want to load... turns out I had to pull something like 60 commits! Now everything works as intended, thanks for the amazing work!

**Comment by 89iuv** [comment] 2023-08-18 06:38
@evanleck I added the option to remove the icon from a module.
Update the plugin to the latest version and use this as an example:

```bash
set -g @catppuccin_status_modules "application session date_time"
set -g @catppuccin_status_left_separator "null"
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "yes"

set -g @catppuccin_application_icon "null"

set -g @catppuccin_session_icon "null"

set -g @catppuccin_date_time_text "%Y-%m-%d | %H:%M:%S"
set -g @catppuccin_date_time_icon "null"
```

<img width="305" alt="image" src="https://github.com/catppuccin/tmux/assets/3298487/c52188e6-4f99-4e91-8003-504318c70874">

**Comment by evanleck** [comment] 2023-08-18 17:16
@89iuv thank you very much! That's working great now, much appreciated.

**Comment by SonMinhNguyen2000** [comment] 2023-08-24 18:37
is there anyway to get this back? I just couldn't make the window item tail look like that.
[powerline](https://raw.githubusercontent.com/catppuccin/tmux/e7b50832f9bc59b0b5ef5316ba2cd6f61e4e22fc/assets/powerline-icons.webp)

**Comment by diego898** [comment] 2023-10-20 18:28
Can you help me understand how to achieve the following now:
- window name is now displayed on the left of the status bar,
- current path is displayed on the right
I just want to swap the current default behavior of the left and right pieces in terms of window name and current window path

**Comment by sgoudham** [comment] 2024-03-09 21:55
Closing this issue as the big plugin update happened several months ago and I'd prefer if people raised individual issues for any problems they are still coming across.

**Closed by sgoudham** 2024-03-09 21:55 UTC
