### ISSUE TITLE
Non-current window is renamed to computer name on Ubuntu / WSL2 

### ISSUE THREAD

**Issue by pietervdheijden** [catppuccin/tmux#421] opened 2024-11-05 05:41 UTC
### I am not requesting help with my configuration and believe something is genuinely broken.

- [X] Something is really actually broken.

### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I am experiencing an issue while using the Catppuccin theme in Tmux on Ubuntu 22.04 running in WSL2. I like this theme and use it successfully with Neovim, but it's causing some unexpected behavior in Tmux on my WSL setup.

**Issue Description:**

When I add the line `set -g @plugin 'catppuccin/tmux` to my `tmux.conf`, any non-current window is automatically renamed to my computer name (CM-4BRP5M3). This behavior is exclusive to my WSL instance; when I use the same configuration on Arch Linux, the window names are preserved as expected.

Notably, the issue is resolved when I do not include the Catppuccin theme plugin in my Tmux configuration.

**Attempted solutions:**

- Added `set-option -g allow-rename off` to my `tmux.conf`.
- Added `export DISABLE_AUTO_TITLE=true` to my `.zshrc`.

Neither solutions resolved the issue.

Could you please provide guidance on resolving this issue? I’m hoping to maintain the Catppuccin theme without the window renaming problem on WSL2.

### Paste your configuration.

```
# Set terminal
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"

# Enable mouse support
set -g mouse on

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Configure Catppuccin theme options (add before the plugins section)
set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, latte
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Preserve current path when splitting window
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# Disable renaming
set-option -g allow-rename off
set-option -g automatic-rename off
set-window-option -g automatic-rename off
```

### Attach screenshots.

When window 2 is active, window 1 and 3 both have my computer name:

![image](https://github.com/user-attachments/assets/8a06b6fb-8ca3-41ff-91a7-75d11795d665)

When window 3 is active, window 1 and 2 both have my computer name:

![image](https://github.com/user-attachments/assets/e94fe831-4de2-4476-aab8-0170e47f6c02)

### What tmux version are you seeing the issue on?

tmux 3.2a

**Comment by kjnsn** [comment] 2024-11-05 06:49
Change this line:

```
set -g @catppuccin_window_default_text "#W"
```

to this:

```
set -g @catppuccin_window_text "#W"
```

**Comment by kjnsn** [comment] 2024-11-05 06:49
This is a dupe of https://github.com/catppuccin/tmux/discussions/412

**Closed by kjnsn** 2024-11-05 06:49 UTC
Labels: bug

**Comment by pietervdheijden** [comment] 2024-11-05 11:57
Excellent, that resolved my problem! It took me a few hours yesterday, so I truly appreciate your prompt response!
